### PR TITLE
#4 - Prettier Implementation

### LINKED ISSUE #4: Plumbing: Prettier
To auto-fix formatting issues, we should implement (& configure) prettier.

### PR DESCRIPTION
**Pull request by aspencer**
Resolves #4

### CODE REVIEW

**Comment by sspencerwire** [comment]
I'm having a terrible time keeping up with things right now. You'd think I would have time!! I've seen "prettier" mentioned before... is it a React or Javascript thing?

**Comment by aspencer** [comment]
Not just JS or React - It will auto-format CSS and HTML as well. Basically it's a way to enforce a consistent style and make PR reviews "real talk", vs complaining on the placement of curly brackets.

**Comment by aspencer** [comment]
You can see in this commit https://github.com/aspencer/vkus/commit/6e64e0b3f8ba6af0fb62ca13cdb2c40d877407ae where it cleaned up the current codebase.

**Review by sspencerwire — COMMENTED** [review]
OK, so this makes perfect sense to me. Keeping a consistent code base formatting makes the code easier to read later on.

**Pull request merged**
